version: '3.4'

services:
  e-comic-sql-server:
    container_name: e-comic-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Huy2002109@
  auth.api:
    container_name: identity-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:Default=Server=e-comic-sql-server;Database=IdentityDb;User Id=sa;Password=Huy2002109@;TrustServerCertificate=True
      - JWT:Key=this is the secret key for authentication
      - JWT:Issuer=http://+:5064
      - JWT:Audience=http://+:5064
    ports:
      - "5064:80"
    depends_on:
      - e-comic-sql-server

  user-api:
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:Default=Server=e-comic-sql-server;Database=UserDb;User Id=sa;Password=Huy2002109@;TrustServerCertificate=True
      - Cloudinary:Url=cloudinary://539265999259773:EJ3KfGkoSkeXX_qq6h0nwX12UoQ@justme2002cloud
      - JWT:Key=this is the secret key for authentication
      - JWT:Issuer=http://+:5064
      - JWT:Audience=http://+:5064
    ports:
      - "5157:80"
    depends_on:
      - e-comic-sql-server


  comic-api:
    container_name: comic-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:Default=Server=e-comic-sql-server;Database=ComicDb;User Id=sa;Password=Huy2002109@;TrustServerCertificate=True
      - Cloudinary:Url=cloudinary://539265999259773:EJ3KfGkoSkeXX_qq6h0nwX12UoQ@justme2002cloud
      - JWT:Key=this is the secret key for authentication
      - JWT:Issuer=http://+:5064
      - JWT:Audience=http://+:5064
    ports:
      - "5016:80"
    depends_on:
      - e-comic-sql-server

