version: '3.4'

services:
  authdb:
    container_name: auth-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Huy2002109@
  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:Default=Server=authdb;Database=IdentityDb;User Id=sa;Password=Huy2002109@;TrustServerCertificate=True
      - JWT:Key=this is the secret key for authentication
      - JWT:Issuer=http://+:5064
      - JWT:Audience=http://+:5064
    ports:
      - "5064:80"
    depends_on:
      - authdb

  user-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

