version: '3.4'

services:
  e-comic-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
  auth.api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: auth-service/API/Dockerfile


  user-api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: user-service/User-API/Dockerfile


  comic-api:
    image: ${DOCKER_REGISTRY-}comicapi
    build:
      context: .
      dockerfile: comic-service/Comic-API/Dockerfile

