version: '3.4'

services:
  auth.api:
    image: api:dev
    container_name: API_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\E_COMIC_PLATFORM_DO_AN_CHUYEN_NGANH_2\back-end\e-comic-back-end\auth-service\API:/app
      - D:\E_COMIC_PLATFORM_DO_AN_CHUYEN_NGANH_2\back-end\e-comic-back-end:/src
      - C:\Users\huy.hoang\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\huy.hoang\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true